### ISSUE TITLE
organise the repo into directories

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/ci-example-code#1]
there are a lot of files in the root of the repo. it would be nice to organise them a bit, e.g. have directories for the server, for the jenkins specific files, for the travis specific files, etc.

**Comment by deitch** [comment]
It isn't as simple as that. I don't mind moving the docs to a `docs/` folder, but the `Jenkinsfile` and the `.travis.yml` **have** to be in the root of the folder. 

So best I can see is:

* Move server stuff to `./server/`
* Move `.md` files except for `README.md` to `docs/`
* Move the test files `test.sh` and `Dockerfile.test` to `test/` folder

`compose.yml` variants, `Makefile`, `Jenkinsfile`, `.travis.yml` all need to stay in root.

Good enough?

**Comment by deitch** [comment]
Quite a bit done. Take a look at it.

**Comment by prisamuel** [comment]
Done.
